version: '3.6'
name: app

services:



  redis:
    build: ./requirements/bonus/redis
    restart: always


  mariadb:
    build: ./requirements/mariadb
    # env_file:
    #   - .env
    restart: always
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - db_volume:/var/lib/mysql
  


  wordpress:
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress
    environment:
      - MYSQL_HOST=mariadb
      - WP_PATH=/srv/www/wordpress
      - WP_TITLE=inception
      - WP_USER_ROLE=editor
    env_file:
      - .env
    restart: always
    volumes:
      - wp_volume:/srv/www/wordpress

  adminer:
    depends_on:
      - wordpress
    build: ./requirements/bonus/adminer
    ports:
      - 8080:8080
    volumes:
      - adminer_volume:/adminer
    restart: always

  nginx:
    depends_on:
      - wordpress
      - adminer
    build: ./requirements/nginx
    ports:
      - 443:443
      # - 80:80
      - 7000:8080
    restart: always
    volumes:
      - wp_volume:/srv/www/wordpress
      - adminer_volume:/adminer
      - $CERTS_:/etc/nginx/ssl:ro



  ftp:
    depends_on:
      - wordpress
    build: ./requirements/bonus/ftp
    ports:
      - 21:21
      # - 20:20
      # - 1024-65535:1024-65535/tcp
      - "21000-21010:21000-21010"
    restart: always
    environment:
      - FTP_USER=$FTP_USER
      - FTP_PASS=$FTP_PASS
    volumes:
      - wp_volume:/srv/ftp
      - $CERTS_:/etc/vsftpd/ssl:ro


  static_website:
    build: ./requirements/bonus/static_website
    ports:
      - 81:80
    restart: always



  # prometheus:
  #   image: prom/prometheus
  #   restart: always
  #   ports:
  #     - "9000:9090"
  #   volumes:
  #     - ./requirements/bonus/prometheus:/etc/prometheus
  #   command:
  #     - '--config.file=/etc/prometheus/prometheus.yml'

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  wp_volume:
  db_volume:
  adminer_volume:
  portainer_data: