services:
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    restart: always
    networks: 
      - inception_net
    image: redis:v1.0

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    networks: 
      - inception_net
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    volumes:
      - db_data:/var/lib/mysql
    image: mariadb:v1.0

  wordpress:
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_started
    build: ./requirements/wordpress
    container_name: wordpress
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_HOST=$MYSQL_HOST
      - WP_PATH=$WP_PATH
      - WP_TITLE=$WP_TITLE
      - WP_USER_ROLE=$WP_USER_ROLE
      - WP_USER=$WP_USER
      - WP_USER_PASSWORD=$WP_USER_PASSWORD
      - WP_USER_MAIL=$WP_USER_MAIL
      - WP_ADMIN=$WP_ADMIN
      - WP_ADMIN_PASSWORD=$WP_ADMIN_PASSWORD
      - WP_ADMIN_EMAIL=$WP_ADMIN_EMAIL
      - DOMAIN_NAME=$DOMAIN_NAME
    restart: always
    networks: 
      - inception_net
    volumes:
      - wp_data:/srv/www/wordpress
    image: wordpress:v1.0

  adminer:
    depends_on:
      wordpress:
        condition: service_started
    build: ./requirements/bonus/adminer
    container_name: adminer
    volumes:
      - adminer_data:/adminer
    restart: always
    networks: 
      - inception_net
    image: adminer:v1.0

  nginx:
    depends_on:
      wordpress:
        condition: service_started
      adminer:
        condition: service_started
    build: ./requirements/nginx
    container_name: nginx
    environment:
      - DOMAIN_NAME=$DOMAIN_NAME
    ports:
      - 443:443
      - 7000:7000
    restart: always
    networks: 
      - inception_net
    volumes:
      - wp_data:/srv/www/wordpress
      - adminer_data:/adminer
    image: nginx:v1.0

  ftp:
    depends_on:
      wordpress:
        condition: service_started
    build: ./requirements/bonus/ftp
    container_name: ftp
    ports:
      - 21:21
      - "21000-21010:21000-21010"
    restart: always
    networks: 
      - inception_net
    environment:
      - FTP_USER=$FTP_USER
      - FTP_PASS=$FTP_PASS
    volumes:
      - wp_data:/srv/ftp
    image: ftp:v1.0

  website:
    build: ./requirements/bonus/website
    container_name: website
    ports:
      - 3000:80
    restart: always
    networks: 
      - inception_net
    image: website:v1.0

  portainer:
    build: ./requirements/bonus/portainer
    container_name: portainer
    restart: always
    networks: 
      - inception_net
    ports:
      - "9000:9000"
      - "9443:9443"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    image: portainer:v1.0

volumes:
  wp_data:
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /home/${USER}/data
  db_data:
    # driver_opts:
      # type: none
      # o: bind
      # device: /home/${USER}/data/
  adminer_data:
    # driver_opts:
      # type: none
      # o: bind
      # device: /home/${USER}/data/
  portainer_data:
    # driver_opts:
      # type: none
      # o: bind
      # device: /home/${USER}/data/

networks:
  inception_net:
