name: myapp

services:

  mariadb:
    build: ./mariadb
    env_file:
      - .env
    volumes:
      - db_volume:/var/lib/mysql
  
  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./wordpress
      dockerfile: Dockerfile
    environment:
      - MYSQL_HOST=mariadb
      - WP_PATH=/srv/www/wordpress
    env_file:
      - .env
    volumes:
      - wp_volume:/srv/www/wordpress


  nginx:
    depends_on:
      - wordpress
    build: ./nginx
    ports:
      - 443:443
    volumes:
      - wp_volume:/srv/www/wordpress

volumes:
  wp_volume:
  db_volume: